version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: jodogne/orthanc-plugins:1.12.4
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - /tmp/orthanc-db/:/var/lib/orthanc/db/
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=HelloWorld


  dbpostgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthanc
      POSTGRES_DB: orthanc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

 

secrets:
  orthanc.json:
    file: orthanc.json
  
